#!/bin/sh -l

module load abaqus/2020

cd $SLURM_SUBMIT_DIR

abaqus job=cranium2 user=NODEMM ask_delete=off cpus=24 -interactive

#To submit job execute this in the command line: "sbatch -t 8:00:00 --nodes=1 --gpus=2 submit_cr"
#CPU task: "sbatch -t 2:00:00 --nodes=1 --ntasks=1 --cpus-per-task=24 submit_cr"
